name: dpl
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  app_links: ^6.4.1
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  provider: ^6.1.5+1

  permission_handler: ^12.0.1
  fast_contacts: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

