// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZQZgOsugqImVHbcHyMfeef4SFO2-5hk',
    appId: '1:457770896149:web:6ca6136c1750fefd3fb71c',
    messagingSenderId: '457770896149',
    projectId: 'flutter-table-app-2026',
    authDomain: 'flutter-table-app-2026.firebaseapp.com',
    storageBucket: 'flutter-table-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEN-DmPeHcHQgbn5KCYTNhVzSo0Z3bOIQ',
    appId: '1:457770896149:android:915616aaec6cb0313fb71c',
    messagingSenderId: '457770896149',
    projectId: 'flutter-table-app-2026',
    storageBucket: 'flutter-table-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQS54RbUEQL_uqnL5ojgPATaTCz1L_9iM',
    appId: '1:457770896149:ios:1d4327c03c8627903fb71c',
    messagingSenderId: '457770896149',
    projectId: 'flutter-table-app-2026',
    storageBucket: 'flutter-table-app-2026.firebasestorage.app',
    iosBundleId: 'com.dream.dpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQS54RbUEQL_uqnL5ojgPATaTCz1L_9iM',
    appId: '1:457770896149:ios:1d4327c03c8627903fb71c',
    messagingSenderId: '457770896149',
    projectId: 'flutter-table-app-2026',
    storageBucket: 'flutter-table-app-2026.firebasestorage.app',
    iosBundleId: 'com.dream.dpl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZQZgOsugqImVHbcHyMfeef4SFO2-5hk',
    appId: '1:457770896149:web:e26f588774e572723fb71c',
    messagingSenderId: '457770896149',
    projectId: 'flutter-table-app-2026',
    authDomain: 'flutter-table-app-2026.firebaseapp.com',
    storageBucket: 'flutter-table-app-2026.firebasestorage.app',
  );
}
